name: update scripts with file-sync
on:
  workflow_dispatch:
  schedule:
    # At 03:03 on Tuesday
    - cron: "3 3 * * 2"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: ./.github/sync.sh jgraph/drawio-libs libs/chart-icons.xml libs/charts/
      
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "update chart-icons"

      - run: ./.github/sync.sh duerrsimon/bioicons static/drawio-lib/Bioicons-Scientific_graphs.xml libs/charts/

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "update Bioicons-Scientific_graphs"

      - run: ./.github/sync.sh duerrsimon/bioicons static/drawio-lib/Bioicons-Lab_apparatus.xml libs/

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "update Bioicons-Lab_apparatus"

      - run: ./.github/sync.sh duerrsimon/bioicons static/drawio-lib/Bioicons-Human_physiology.xml libs/

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "update Bioicons-Human_physiology"

      - run: ./.github/sync.sh jgraph/drawio-libs README.md ./

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "update README"

      - run: ./.github/sync.sh jgraph/drawio-libs LICENSE ./

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "update LICENSE"
